language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - "pip install pep8 coverage coveralls"
  - "pip install -r requirements.txt"
before_script:
  - "./pep8.sh"
  - "export LC_TIME=en_GB"
  - "export LANGUAGE=en_GB"
script:
  "coverage run --source=flask_table setup.py test"
after_success:
  coveralls
